---
- hosts: all
  become: yes

  vars:
      wordlists:
          wfuzz:
            site: https://github.com/xmendez/wfuzz.git
          Seclists:
            site: https://github.com/danielmiessler/SecLists.git
          fuzzdb:
            site: https://github.com/fuzzdb-project/fuzzdb.git
          node-dirbuster:
            site: https://github.com/daviddias/node-dirbuster.git
          dirb:
            site: https://github.com/v0re/dirb.git
      enum:
        linux-smart-enumeration:
          site: https://github.com/diego-treitos/linux-smart-enumeration.git
        LinEnum:
          site: https://github.com/rebootuser/LinEnum.git
        htbenum:
          site: https://github.com/SolomonSklash/htbenum.git
        enum4linux:
          site: https://github.com/portcullislabs/enum4linux.git
      exploits:
        MS17-010:
          site: https://github.com/worawit/MS17-010.git
        AutoBlue-MS17-010:
          site: https://github.com/3ndG4me/AutoBlue-MS17-010.git
        PrivExchange:
          site: https://github.com/dirkjanm/PrivExchange.git
        PowerSploit:
          site: https://github.com/PowerShellMafia/PowerSploit.git
  tasks:
  #added some debuging while messing w/ the dict functions
  #
  - name: debug github names
    debug:
      msg: "{{ item.value.site }}"
    with_dict: "{{ exploits }}"
    tags: msg,never

  - name: Install list of packages
    action: apt pkg={{item}} state=installed
    with_items:
      - traceroute
      - net-tools
      - telnet
      - cifs-utils
      - rlwrap
      - iputils-ping
      - git
      - xsltproc
      # I don't want zsh so removing this 
      # - zsh
      - curl
      - p7zip-full
      - locate
      - openvpn
      - vim
      - wget
      - ftp
      - apache2
      - squid
      - python3
      - python
      - python-pip
      - python3-pip
      - libcurl4-openssl-dev
      - libssl-dev
      - nmap
      - netcat
      # evil-winrm
      - ruby-full
      # enum4linux dependencies
      - ldap-utils
      - smbclient
      # john dependencies
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - yasm
      - pkg-config
      - libgmp-dev
      - libpcap-dev
      - libbz2-dev
      # crackmapexec dependencies
      - libffi-dev
      - python-dev

  - name: create default html page
    copy:
      dest: "/var/www/html/index.html"
      content: "It works!!!!"
  - name: pip3 install     
    #Uses what ever version of python ansible is using!
    pip:
      name:
        - pycurl==7.43.0.3
        - wfuzz
        # ldapdomaindump dependencies
        - ldap3
        - dnspython
    tags: pip3,python
  - name: Create Tools directory if it does not exist
    file:
      path: /tools
      state: directory
      mode: '0755'
    tags: wordlists,create
  
  - name: create the wordlists dir
    file:
      path: /tools/wordlists
      state: directory
      mode: '0755'
    tags: wordlists,dir
  - name: wordlist installs
    git:
      repo: "{{ item.value.site }}"
      dest: "/tools/wordlists/{{ item.key }}"
      update: yes
      depth: 1
      force: yes
    with_dict: "{{ wordlists }}"
    tags: wordlists,git,install
    
    
  # Install searchsploit stuff
  - name: install searchsploit dir
    file:
      path: /opt/exploitdb
      state: directory
      mode: '0755'
    tags: searchsploit,dir
  - name: git clone searchsploit
    git:
      repo: https://github.com/offensive-security/exploitdb.git
      dest: /opt/exploitdb
    tags: searchsploit,git
    #need to add searchsploit to the path.. but for now.. 
    #full path it. or alias import_tasks

  - name: git clone enum tools
    git:
      repo: "{{ item.value.site }}"
      dest: "/tools/enum/{{ item.key }}"
    with_dict: "{{ enum }}"
    tags: enum,git
  #-name: future chmod +x on the above .sh files.. will look at later

  - name: impacket git clone
    git: 
      repo:  https://github.com/SecureAuthCorp/impacket.git
      dest: /tools/impacket
    register: pipmyride
    tags: impacket,git
  - name: compile  impacket
    command: /usr/bin/pip3 install /tools/impacket/
    when: pipmyride
    tags: impacket
  - name: ldapdomaindump
    git:
      repo: https://github.com/dirkjanm/ldapdomaindump.git
      dest: /tools/ldapdomaindump
      depth: 1
      force: no
    register: ldapmyride
    tags: ldapdomaindump
  - name: setup ldapdomaindump
    shell: "cd /tools/ldapdomaindump;/usr/bin/python3 /tools/ldapdomaindump/setup.py install"
    when: ldapmyride
    tags: ldapdomaindump

  - name: rockyou download
    get_url: 
      url: https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
      dest: /tools/wordlists/rockyou.txt
      mode: '644'
    tags: rockyou
  - name: install evil-winrm
    #had trouble with the binary getting put into the path using the ansible gem module. So just shelled this
    # something was wrong w/ rubyenv possibly will fix oneview_logical_interconnect_group_facts
    shell: "gem install evil-winrm"
    tags: evil-winrm

# Looks like these need the installer ran via python.. but maybe 
# the requirements are already met.  So will research
  - name: install smbmap
    git:
      repo: https://github.com/ShawnDEvans/smbmap.git
      depth: 1
      dest: /tools/smbmap
    tags: smbmap
  - name: Install crackmapexec
    git:
      repo: https://github.com/byt3bl33d3r/CrackMapExec
      recursive: yes
      dest: /tools/crackmapexec
    tags: crackmapexec

  - name: Install exploits
    git:
      repo: "{{ item.value.site }}"
      dest: "/tools/exploits/{{ item.key }}"
    with_dict: "{{ exploits }}"
    tags: exploits,git
  
#Need to add squid stuff in here!
  - name: squid install
    debug:
      msg: "get to work"
    tags: squid,never
  

  